### ISSUE TITLE
Call to undefined function bolt_encrypt()

### ISSUE THREAD

**Issue by shukla-rohit** [arshidkv12/phpBolt#1]
Thank you for smart tool, but its not working when I am trying to encrypt through bolt_encrypt,

I checked for 2 different machine.

PHP Fatal error:  Uncaught Error: Call to undefined function bolt_encrypt() in /srv/www/vhosts/*/phpBolt-encrypt/phpBolt-encrypt/index.php:44
Stack trace:
#0 {main}
  thrown in /srv/www/vhosts/*/phpBolt-encrypt/phpBolt-encrypt/index.php on line 44

**Comment by arshidkv12** [comment]
Your configuration is not correct. That is you getting undefind function
error.
Sorry... I can't provide free support.

Regards

**Comment by shukla-rohit** [comment]
bolt_decrypt is working for one of test file, but when trying to encrypt with dummy code provided, thats not working.

Please check this if possible.

**Comment by arshidkv12** [comment]
Please note, many people are installed without any problem.

Regards

**Comment by shree94mashal** [comment]
Hello Arshidkav12,
I have tried this on the Ubuntu and windows both by downloading the extension and enable it on php.ini and restart the apache2 then used the sample code but no luck for me as well 
Can you please the issue 
Thanks

**Comment by arshidkv12** [comment]
Sorry.... No free support.

**Comment by shukla-rohit** [comment]
Its pretty simple steps

Downl

**Comment by shukla-rohit** [comment]
Support is good when things are running, and having some issue, but in this case its not working at all. Anyway thank you for this tool, will check other tool like ioncube(encoding) and others.

Thank you for your help. If any assistance, will connect with you.

**Comment by arshidkv12** [comment]
phpBolt now working with windows also.

**Comment by a-bahrami** [comment]
hi  , i am using webserver ubuntu 20.4  , and i,m using php7.4 after installion bolt everything in command line completely working but when i using url give me error

`
Error
Call to undefined function bolt_decrypt()
`

thanks for helping

**Comment by KTN1990** [comment]
a-bahrami use this command sudo systemctl restart php7.4-fpm.service

**Comment by amjiddader** [comment]
Here is the solution.. 

You are encrypting using CLI ??
and you have added extension on in php/7.2/apache2/php.ini file ..

it shoul be also added in /etc/php/7.2/cli/php.ini 
after adding run : systemctl restart apache2 
It should be workin .

( in apache2/php.ini extension is used to decode file)

**Comment by rhidayatrhd** [comment]
Hi..
I am using windows 10 in my PC and I want to use encrypt/decrypt in my php code.
I get problem :
PHP Warning:  PHP Startup: Unable to load dynamic library 'bolt' (tried: ./ext/bolt (The specified module could not be found), ./ext/php_bolt.dll (The specified module could not be found)) in Unknown on line 0

thanks for helping
