### ISSUE TITLE
encrypt php

### ISSUE THREAD

**Issue by Tech-abm** [arshidkv12/phpBolt#10]
`Not working `

**Comment by hacfi** [comment]
@Tech-abm You need to be more specific so you can get some support. What operating system are you on? Which PHP version and which version of phpBolt do you use? What is `not working`? Which command do you run that doesn't work? Is there an error message?

**Comment by Tech-abm** [comment]
Bro, I have 2 Question...

`01` Your phpBolt commnad is not working. When i run it 👇👇 it![Screenshot_20200829-123755.png](https://user-images.githubusercontent.com/52023076/91631649-0cf27480-e990-11ea-9a42-21514d95bc54.png)

`02` How to decrypt Python Code.. I don't understand what is this. So, you give me, how to decrypt python code 👇
![Screenshot_20200826-183456.png](https://user-images.githubusercontent.com/52023076/91631698-60fd5900-e990-11ea-8f0b-d5667924539c.png)

**Comment by hacfi** [comment]
1. To get this to work you need to create some php code in the path `src/noti`:

```sh
mkdir -p src/noti
echo '<?php echo "hello world";' > src/noti/test.php
php encryption.php
```
it should output `Successfully Encrypted... Please check in <b>...path/to/phpBolt/encrypted/noti</a></b> folder.%`

to run the encrypted code you need to use the same key that was used for encryption which in this case is `kyc7fh` (https://github.com/arshidkv12/phpBolt/blob/master/encryption.php#L9).

You can test this like this:
```
php -r "define('PHP_BOLT_KEY', 'kyc7fh'); include('encrypted/noti/test.php');"
```

Of course you need to have the phpBolt extension properly installed! See https://phpbolt.com/download-phpbolt/

2. This is not the right place to ask how to decrypt that Python code but have a look at https://docs.python.org/3/library/marshal.html to understand more what the marshal module does.

**Comment by Tech-abm** [comment]
` Thank You `
