### ISSUE TITLE
Required support for php 7.4

### ISSUE THREAD

**Issue by dipenparmar12** [arshidkv12/phpBolt#11]
Hi team,
I am using  **laravel 7.26.1** with **php 7.4** but i didn't find **bolt.so** file for **php 7.4** for **linux 64** arc.
What i can do to resolve this.

**Comment by hacfi** [comment]
@dipenparmar12 Wait for @arshidkv12 to release a PHP 7.4 version. I asked about this via the chat on phpbolt.com but haven't heard back.

**Comment by arshidkv12** [comment]
I will make a new phpbolt version (v2) in php7.4

**Comment by alexandruflorea** [comment]
@arshidkv12 Can you estimate the release date for phpbolt for php7.4 ? Thanks.

**Comment by arshidkv12** [comment]
Within 14 days

**Comment by alexandruflorea** [comment]
@arshidkv12 do you have any updates ? 😄

**Comment by artdian** [comment]
@arshidkv12  I think we need info update for php 7.4 sir 😄

**Comment by arshidkv12** [comment]
Download the new version https://phpbolt.com/wp-content/uploads/2020/11/phpBolt-extension-1.0.2.zip

**Comment by airthomas** [comment]
> Download the new version https://phpbolt.com/wp-content/uploads/2020/11/phpBolt-extension-1.0.2.zip

Many thanks for your work.

**Comment by MustafaHussaini** [comment]
what about php8 support?
The php7.4 release also has some issues on latest release of xampp 7.4 on windows os.
This issue https://github.com/arshidkv12/phpBolt/issues/8#issue-589752533
I think the difference between xampp build version  and php_bolt.dll causes this issue.
