### ISSUE TITLE
Undefined function bolt errors. 

### ISSUE THREAD

**Issue by shehlizah** [arshidkv12/phpBolt#12]
I have downloaded the code and your loader, added the extension code in php.ini file but still it gives me the following issue for both bolt_decrypt() and bolt_encrypt().

Fatal error: Uncaught Error: Call to undefined function bolt_decrypt() in C:\xampp\htdocs\phpBolt-encrypt\encrypted\hello\index.php:6 Stack trace: #0 {main} thrown in C:\xampp\htdocs\phpBolt-encrypt\encrypted\hello\index.php on line 6

**Comment by arshidkv12** [comment]
Install bolt.so properly
