### ISSUE TITLE
Will this maake application slow?

### ISSUE THREAD

**Issue by twf-nikhila** [arshidkv12/phpBolt#16]
Hi,

Just want to give it a try with laravel application. Will this make the application slow?

**Comment by hall-of-code** [comment]
Why your closing the Issue without anwering. I think its realy interesting to know whats about Security reasons and how stabile and fast a encrypter Laravel App is. ;)

**Comment by arshidkv12** [comment]
It is a free extension. You can download and test (benchmark )
