### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by egi-munandar** [arshidkv12/phpBolt#18]
When will phpbolt support php 8?

**Comment by cpjones44** [comment]
+ 1

**Comment by hschimpf** [comment]
Hi! firstly, awesome work of this extension. 2nd, please are we getting PHPv8 support? Will be amazing

**Comment by hoowa** [comment]
i put new php encoder project in github, it supported PHP 8.X and JIT enviroment. access https://github.com/hoowa/PHP-FRICC2 for details.

**Comment by hotplumzao** [comment]
All Github  search "php8 encode"

**Comment by SiavashBamshadnia** [comment]
any news?

**Comment by MrMuminov** [comment]
?

**Comment by pety-dc** [comment]
up

**Comment by arshidkv12** [comment]
Released so file for php 8 and 8.1

**Comment by SiavashBamshadnia** [comment]
Thank you. And what about the dll file?

**Comment by MrMuminov** [comment]
Ooo yeah, thanks.

**Comment by pety-dc** [comment]
Thank you!

**Comment by Shaz3e** [comment]
upvote

**Comment by quannahe140579** [comment]
upvote

**Comment by AhmedBoyka** [comment]
upvote

**Comment by Avinash14012002** [comment]
can you provide zip file link. i can't able to get the php bolt v8

**Comment by mrmuminov** [comment]
> can you provide zip file link. i can't able to get the php bolt v8

@Avinash14012002, Go to official site and fill the form on the download page, then, they will send it to your email.

**Comment by Avinash14012002** [comment]
yeah i tried so many times. once i click download button after enetring the details i get the message "Please check your inbox. You will get download link", but i didn't get any mail

**Comment by Avinash14012002** [comment]
Hi everyone,

Could someone kindly provide the ZIP download link for PHP Bolt v8? I would really appreciate it.

Thank you in advance!

**Comment by Avinash14012002** [comment]
Hi everyone,

I hope you're all doing well.

I'm in urgent need of PHP Bolt v8 and would greatly appreciate it if someone could provide me with the ZIP download link. Your assistance in this matter would be incredibly valuable to me.

Thank you very much in advance for your help!

**Comment by egi-munandar** [comment]
You can find it [here](https://github.com/arshidkv12/phpBolt/issues/40#issuecomment-2220463233)

**Comment by Avinash14012002** [comment]
Hi everyone,

Thank you for your assistance earlier. However, the link provided contains an older version of PHP Bolt with PHP 7.4, but I’m specifically looking for PHP Bolt that supports PHP 8.

If anyone has access to the ZIP file for PHP Bolt v8 (with PHP 8 support), I would be very grateful if you could share it with me.

Thank you so much for your help!

**Comment by egi-munandar** [comment]
It does have the version 8, just not for windows.
May be you looking for windows version?
![image](https://github.com/user-attachments/assets/c44e7d42-f174-4e7b-b746-0c61b63da0c1)

**Comment by Avinash14012002** [comment]
It seems that version 8 is available, but not for Windows. I'm specifically looking for version 8 for Windows. If you have any information on where I can find it or when it will be available, I would appreciate it.

Thank you so much for your help!

**Comment by arif98741** [comment]
> It does have the version 8, just not for windows. May be you looking for windows version? ![image](https://private-user-images.githubusercontent.com/78336093/366387377-c44e7d42-f174-4e7b-b746-0c61b63da0c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDE3MTksIm5iZiI6MTczMjAwMTQxOSwicGF0aCI6Ii83ODMzNjA5My8zNjYzODczNzctYzQ0ZTdkNDItZjE3NC00ZTdiLWI3NDYtMGM2MWI2M2RhMGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MTc1MGQ4ODUzYThjNDFjN2UwMmI2YjUyMjYzOWE2OGE1ZDAxYmRhYjA5MWNjOTBmMzc0YjdjYmViNjA5ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Zu-jOXOPrdLof7U5mxe0AN_wLGWeWjdn9z5Y8xqdyM)

can you provide this file to me? because I am not getting file from website.

**Comment by lokeshfitsys** [comment]
> > It does have the version 8, just not for windows. May be you looking for windows version? ![image](https://private-user-images.githubusercontent.com/78336093/366387377-c44e7d42-f174-4e7b-b746-0c61b63da0c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDE3MTksIm5iZiI6MTczMjAwMTQxOSwicGF0aCI6Ii83ODMzNjA5My8zNjYzODczNzctYzQ0ZTdkNDItZjE3NC00ZTdiLWI3NDYtMGM2MWI2M2RhMGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MTc1MGQ4ODUzYThjNDFjN2UwMmI2YjUyMjYzOWE2OGE1ZDAxYmRhYjA5MWNjOTBmMzc0YjdjYmViNjA5ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Zu-jOXOPrdLof7U5mxe0AN_wLGWeWjdn9z5Y8xqdyM)
> 
> can you provide this file to me? because I am not getting file from website.

Use this link to download. [phpBolt-extension-1.0.5.zip](https://phpbolt.com/wp-content/uploads/2024/03/phpBolt-extension-1.0.5.zip)

**Comment by mohanlokesh** [comment]
> It seems that version 8 is available, but not for Windows. I'm specifically looking for version 8 for Windows. If you have any information on where I can find it or when it will be available, I would appreciate it.
> 
> Thank you so much for your help!

Yes you're right, there is no 8 version available for windows they given only linux support.

**Comment by mohanlokesh** [comment]
> > It does have the version 8, just not for windows. May be you looking for windows version? ![image](https://private-user-images.githubusercontent.com/78336093/366387377-c44e7d42-f174-4e7b-b746-0c61b63da0c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDE3MTksIm5iZiI6MTczMjAwMTQxOSwicGF0aCI6Ii83ODMzNjA5My8zNjYzODczNzctYzQ0ZTdkNDItZjE3NC00ZTdiLWI3NDYtMGM2MWI2M2RhMGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MTc1MGQ4ODUzYThjNDFjN2UwMmI2YjUyMjYzOWE2OGE1ZDAxYmRhYjA5MWNjOTBmMzc0YjdjYmViNjA5ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Zu-jOXOPrdLof7U5mxe0AN_wLGWeWjdn9z5Y8xqdyM)
> 
> can you provide this file to me? because I am not getting file from website.


Use this link to download. [phpBolt-extension-1.0.5.zip](https://phpbolt.com/wp-content/uploads/2024/03/phpBolt-extension-1.0.5.zip)
