### ISSUE TITLE
php 8.2 support

### ISSUE THREAD

**Issue by jamesRUS52** [arshidkv12/phpBolt#29]
Please add php 8.2 support

**Comment by jamesRUS52** [comment]
@arshidkv12 do you plan release that or project is dead?

**Comment by arshidkv12** [comment]
I will release it soon.

**Comment by jamesRUS52** [comment]
> I will release it soon.


How are you? )

**Comment by jamesRUS52** [comment]
> Download new files: https://phpbolt.com/wp-content/uploads/2023/03/phpBolt-extension-1.0.4.zip

Thank you, very much. 
I see the linux 64-php8.2.so reduce size up to 2 times from 30.9 kB to 18,5 kB, it's normal or has some limitation ?

**Comment by mrmuminov** [comment]
![image](https://user-images.githubusercontent.com/64766486/224090677-80e783a6-e363-45e6-8e77-bd4453910fa0.png)
Error on opening time.

**Comment by jamesRUS52** [comment]
@arshidkv12 Thanks a lot again.
I have performed small test, and it work with simple files.

I check the old bug also, and it still occures like in 8.1
The problem with anonymous classes
Do you have a plan to fix it?

```   Error 

  Class "Test2" not found

  at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:533
    529▕                     ? $this->files->getRequire($path)
    530▕                     : clone $migration;
    531▕         }
    532▕ 
  ➜ 533▕         return new $class;
    534▕     }
    535▕ 
    536▕     /**
    537▕      * Generate a migration class name based on the migration file name.

      +19 vendor frames 

  20  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
