### ISSUE TITLE
 Not available

### ISSUE THREAD

**Issue by JiangQinZhe** [arshidkv12/phpBolt#7]
Subject: Not available
Environment: PHP7.3.5
Why?PHP warning:
Warning: Unexpected character in input: '' (ASCII=3) state=0 in

**Comment by arshidkv12** [comment]
Add correct key.

**Comment by JiangQinZhe** [comment]
Resolved.
At the same time, I would like to ask if there is a separate bolt_decrypt so/dll compilation file (without encryption function).
