### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'bolt' (tried: C:\xampp\php\ext\bolt (The specified module could not be found.), C:\xampp\php\ext\php_bolt.dll (%1 is not a valid Win32 application.)) in Unknown on line 0

### ISSUE THREAD

**Issue by prasanth22** [arshidkv12/phpBolt#8]
[
![Screenshot (233)](https://user-images.githubusercontent.com/34378827/77845499-02f3fc00-71cd-11ea-87ce-95ee2ec343b4.png)
](url)

**Comment by prasanth22** [comment]
i am using windows 10 and XAMPP with php version 7.3

**Comment by mohammedSabbar** [comment]
Try add this line in php.ini after copy the php_bolt.dll in the right path 

extension="C:\xampp\php\ext\php_bolt.dll"

**Comment by shqawe1** [comment]
I have the same problem i'm using windows 10 too i tried Mohammed solution but it doesn't work
 any idea about this issue?

**Comment by dipenparmar12** [comment]
Seems like in `php.ini`  extension directory is wrong.
try this 
`extension_dir = "ext"` 
> Make sure semicolon (`;`) is removed before  `extension_dir `

or if above not work then try this

`extension_dir = "absulate_path_of_extension"` 

For me **Windows 10**  with **php7.3** working fine.

**Comment by truptinikhade** [comment]
Unable to load dynamic library 'bolt' (tried: C:\xampp\php\ext\bolt (The specified module could not be found.), C:\xampp\php\ext\php_bolt.dll (The specified module could not be found.)) in Unknown on line 0
ERROR: Please run composer install


How to solve this error

**Comment by Tarhex** [comment]
The `php_bolt.dll` file is for `Win x64` and not `Win x32` as rightly placed in the `Win x64` folder downloaded from the phpBolt website. You need a PHP version for Win x64
